### ISSUE TITLE
Add FerriteCore and previously used game enhancement mods

### ISSUE THREAD

**Issue by TheOne2160** [tungstonminer/blocky-go-round#15]
### What is the problem you're trying to solve with this change?

fix the various performance and memory problems

### What do you propose as a solution?

add FerriteCore and other mods from the Austere Caves pack

**Comment by tungstonminer** [comment]
I know I got a bunch of them already, but it's worth double-checking.  Here are all the performance-enhancing mods from Austere Caves.  I'll double-check to make sure they all make it into Blocky Go Round.

* AI Improvements
* BetterFPS
* Clumps
* DynamicView
* FerriteCore
* FPSReducer

**Comment by TheOne2160** [comment]
Just reviewed the mod list, that seems to be all of them. Thanks!
