### ISSUE TITLE
Add the Tetra Mod

### ISSUE THREAD

**Issue by TheOne2160** [tungstonminer/blocky-go-round#41]
### What is the problem you're trying to solve with this change?

The tetra mod is a great mod that fits into the Create theme of this pack. You can make custom tools with different parts, but its different from Tinkers construct as there is no smelting.

### What do you propose as a solution?
https://www.curseforge.com/minecraft/mc-mods/tetra

**Comment by tungstonminer** [comment]
Tetra is already in the modpack.
