### ISSUE TITLE
No Shield Crafting Recipe

### ISSUE THREAD

**Issue by TheOne2160** [tungstonminer/blocky-go-round#42]
### What is the problem you're trying to solve with this change?
Cannot craft a shield in survival

### What do you propose as a solution?
not sure

**Comment by tungstonminer** [comment]
What are you seeing that makes you say that?  The recipe *has* changed, but it works fine for me.

**Comment by TheOne2160** [comment]
In JEI, the recipe is wrong

**Comment by TheOne2160** [comment]
well, in JEI the recipe doesnt exist

**Comment by tungstonminer** [comment]
Hmm.  Here's what I have:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/72411157/166087582-abada722-856a-4e77-9dc0-2dcb099c5b2a.png">

Can you double-check that your `scripts` directory has a `50_vanilla.zs` file in it?   The new recipe for the shield should be in there.

**Comment by tungstonminer** [comment]
It looks like there are a lot of recipes which are affected, each of them using the ZenScript `|` operator.  They all work correctly on a single-player world, but any recipe ingredient which uses the `|` operator simply doesn't show up at all on the server.  I've checked everything I can think of, and nothing seems to make any sense to me.  So, I've [posted a question](https://discord.com/channels/136877912698650625/354745056743260172/970169594985721866) on the official CraftTweaker Discord channel.  We'll see if anything helpful comes from it.

**Comment by tungstonminer** [comment]
Naturally, there are quite a few recipes affected by this problem: iron tools, arms, and armor; backpacks; shields, and quite a few others.  I would expect them all to be resolved by the same fix.

**Comment by tungstonminer** [comment]
I'm going to close this issue as I solved a number of similar problems with #45.  Please re-open if you're still having problems.
