### ISSUE TITLE
Server Access Request

### ISSUE THREAD

**Issue by datboill123** [tungstonminer/blocky-go-round#46]
### Please answer the following questions

*What is your experience playing modded Minecraft?*I paly with friends and have used mod packs before 

*Have you successfully been able to play *this modpack* in single-player?*yes

*What is your Minecraft username?* Pamul0

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered
once per day, so you should generally receive a response in less than 24h.  In the meantime, you can
set up your Minecraft instance to access the server at:

`blockygoround.sparkedservers.us`

Finally, it is *highly recommended* that you read [the
wiki](https://github.com/tungstonminer/blocky-go-round/wiki) for the modpack.  You'll find it
provides a lot of useful information about where to find things, what mods are available, and what
changes have been made to the regular vanilla game.

**Comment by tungstonminer** [comment]
That all sounds good!  You've been added to the whitelist.  Check out the Discord server if you have any questions.
