### ISSUE TITLE
Please sir, can I get whitelisted?

### ISSUE THREAD

**Issue by GnarlyOldGuy** [tungstonminer/blocky-go-round#63]
### Please answer the following questions

*What is your experience playing modded Minecraft?*

I've played on your servers in the past. Ishtari the last I believe.

*Have you successfully been able to play *this modpack* in single-player?*

Yes

*What is your Minecraft username?*

GnarlyOldGuy

### Please re-state the server rules in your own words

No hacking
Be respectful
No stealing
No griefing
No killing

### Next Steps

Please be patient while waiting for your request to be considered!  Access requests are considered
once per day, so you should generally receive a response in less than 24h.  In the meantime, you can
set up your Minecraft instance to access the server at:

`blockygoround.sparkedservers.us`

Finally, it is *highly recommended* that you read [the
wiki](https://github.com/tungstonminer/blocky-go-round/wiki) for the modpack.  You'll find it
provides a lot of useful information about where to find things, what mods are available, and what
changes have been made to the regular vanilla game.

**Comment by tungstonminer** [comment]
All set!  Welcome back!
